# initializing backend - https://gitlab.com/gitlab-org/gitlab/-/blob/v14.6.7-ee/doc/user/infrastructure/iac/terraform_state.md

default:
  image:
    name: hashicorp/terraform
    entrypoint: [""] # to override the default entrypoint command
  timeout: 15 minutes
  cache:
    - key: $CI_PIPELINE_ID-terraform-cache
      paths:
        - .terraform/
        - .terraform.lock.hcl

variables:
  TF_USERNAME: ${GITLAB_USERNAME}
  TF_PASSWORD: ${GITLAB_TOKEN}
  STATEFILE_NAME: "terraform.tfstate"
  TF_ADDRESS: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/terraform/state/${STATEFILE_NAME}"

stages:
  - format
  - init
  - validate
  - apply
  - configure
  - destroy

format-job:
  stage: format
  script:
    - terraform fmt
  cache: []
  allow_failure: true

download-provider:
  stage: init
  script:
    - |
      terraform init \
        -backend-config=address=${TF_ADDRESS} \
        -backend-config=lock_address=${TF_ADDRESS}/lock \
        -backend-config=unlock_address=${TF_ADDRESS}/lock \
        -backend-config=username=${TF_USERNAME} \
        -backend-config=password=${TF_PASSWORD} \
        -backend-config=lock_method=POST \
        -backend-config=unlock_method=DELETE \
        -backend-config=retry_wait_min=5

validate:
  stage: validate
  script:
    - terraform validate

apply-configuration:
  stage: apply
  script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - terraform apply -auto-approve
  artifacts:
    name: "$CI_JOB_NAME-$CI_JOB_ID"
    paths:
      - ./hosts # because we need to have this host file for the ansible job
    expire_in: 1 day

ansible:
  image:
    name: alpinelinux/ansible
    entrypoint: [""]
  stage: configure
  script:
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ansible-playbook -i hosts install-apache.yml
  cache: []

destroy-infra:
  when: manual
  stage: destroy
  script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - terraform destroy -auto-approve
