# initializing backend - https://gitlab.com/gitlab-org/gitlab/-/blob/v14.6.7-ee/doc/user/infrastructure/iac/terraform_state.md

default:
  image:
    name: hashicorp/terraform
    entrypoint: [""] # to override the default entrypoint command
  timeout: 15 minutes

variables:
  TF_USERNAME: ${GITLAB_USERNAME}
  TF_PASSWORD: ${GITLAB_TOKEN}
  STATEFILE_NAME: "terraform.tfstate"
  TF_ADDRESS: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/terraform/state/${STATEFILE_NAME}"

stages:
  - format
  - init
  - validate

format-job:
  stage: format
  script:
    - terraform fmt

download-provider:
  stage: init
  script:
    - |
      terraform init \
        -backend-config=address=${TF_ADDRESS} \
        -backend-config=lock_address=${TF_ADDRESS}/lock \
        -backend-config=unlock_address=${TF_ADDRESS}/lock \
        -backend-config=username=${TF_USERNAME} \
        -backend-config=password=${TF_PASSWORD} \
        -backend-config=lock_method=POST \
        -backend-config=unlock_method=DELETE \
        -backend-config=retry_wait_min=5

validate:
  stage: validate
  script:
    - terraform validate
